### ISSUE TITLE
hosted form

### ISSUE THREAD

**Issue by mergingseas** [j-em/react-authorize-net#11]
is this example showing the hosted form of accept.js?

**Comment by j-em** [comment]
The library currently doesn't make use of the hosted payment form.
If you need to quickly have a nice and functional payment form, I suggest using `<FormContainer />` with `<FormComponent />`.
This should be as easy (even easier because of the native react api) as using the hosted payment form.
Don't hesitate to reach out if you have any other questions!

**Comment by mergingseas** [comment]
Thanks for your response, the only issue is regarding PCI-DSS SAQ A.  The hosted form is PCI-DSS SAQ A compliant.  If we build our form is it still pci compliant?

**Comment by j-em** [comment]
Since ``<FormContainer />`` stores and manipulate card data locally, it's my understanding that this would make it PCI-DSS SAQ **A-EP** compliant only.

With that being said, I think that is a use case that the library should support.
Thanks for taking the time to report this. 👍🏻

**Comment by j-em** [comment]
@mergingseas You should now be able to build fully SAQ-A compliant forms using the latest beta version of the package: https://www.npmjs.com/package/react-authorize-net/v/0.5.1#accepthosted-

If you have any issues to report while using the beta release, please don't hesitate to open a new issue.
