### ISSUE TITLE
Authorize.net not processing transaction

### ISSUE THREAD

**Issue by rweidman** [j-em/react-authorize-net#30]
Data is flowing between authorize.net and my react app, and I receive success message, but the card is never actually charged.  Here is my FormContainer:

<FormContainer
                environment="production"
                onError={onErrorHandler}
                onSuccess={onSuccessHandler}
                amount={1}
                component={FormComponent}
                clientKey={clientKey}
                apiLoginId={apiLoginId}</FormContainer>

Two requests are sent to Authorize.net.  The first is an empty OPTIONS request which comes back with "Error reading JToken from JsonReader. Path '', line 0, position 0."

The second request is a POST request and contains the card data which returns a resultCode of "OK" and a message of "Successful."

Is there another option I need to pass to get this to work?

**Comment by yosepkim** [comment]
Having the same issue.

**Comment by stmiller-shamrock** [comment]
I am having the same issue in the Sandbox. On the client side, I get a success message. In the sandbox, there are no transactions

**Comment by amirsaeed671** [comment]
I have an issue as well, I am able to use test Credit card and my environment has been set to production...... and the request got successfull as well

```
<FormContainer
        environment="production"
        onError={({ messages: { message: errorMessage = [] } }) => {
          const msg = errorMessage[0].text;
          openNotify(msg, true);
        }}
        onSuccess={onSuccess}
        render={(props) => <CustomFormUX {...props} />}
        amount={state.pay}
        clientKey={clientKey}
        apiLoginId={apiLoginId}
      />
```

**Comment by amirsaeed671** [comment]
@j-em , can you help us?

**Comment by yosepkim** [comment]
@amirsaeed671 and @stmiller-shamrock I am not sure if you are having the issue still. I learned that this was actually intended behavior. Basically, the React component basically makes a call to Authorize.net to get an one-time payment token known as a nonce. If the CC is a valid one, then you will receive a successful response with a nonce. However, if it is not valid, you will still get a successful response but this time with error messages. I wondered why you would get a successful response when it in fact failed. This is because, from Authorize.net's perspective, they did process the request successfully. It was the payment processor who declined the CC producing error messages.

Anyway, once you receive the nonce from Authorize.net in your React code, it is your job to make a call to your backend (API) to complete the rest of the transaction, basically, to charge your customer _using_ the nonce by calling one of their [payment endpoints](https://developer.authorize.net/api/reference/features/payment_transactions.html). This double-hop approach was designed so that you don't have to flow or process any CC information through your network or system(s), saving you from the headache of the PCI compliance level D. 

I hope this helps.

**Comment by amirsaeed671** [comment]
Thanks @yosepkim

**Comment by j-em** [comment]
Hello!

Sorry for the long delays - I had very limited time to put towards react-authorize-net these past few months.

This issue can be explained by essentially what @yosepkim said above.

I'll also update the documentation to be more specific about this - since it seems to be affecting multiple people.

Don't hesitate to re-open if you are still having issues.

Cheers!
